"""
Sovereign text ingestion pipeline powered by the RPN embedding engine.

Replaces the legacy GloVe bootstrap with fully sovereign character-trigram
embeddings generated by :class:`RPNEmbeddingEngine`. All downstream processing
remains compatible with the specialised sovereign bridges.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Sequence

import numpy as np

from knowledge3d.cranium.bridges.sovereign_bridges import (
    GraphCrystallizer,
    OOMSpillManager,
    VectorResonator,
)
from knowledge3d.cranium.rpn_embedding_engine import RPNEmbeddingEngine

_DEFAULT_EMBEDDING_STORE = Path("/K3D/Knowledge3D.local/house_zone7/embeddings/rpn_embeddings.pkl")


def _reduce_to_3d(matrix: np.ndarray) -> np.ndarray:
    """
    Reduce an (N, D) matrix to (N, 3) using an SVD-based PCA implementation.

    Pure NumPy so it stays dependency-light. Assumes matrix is float32.
    """
    if matrix.dtype != np.float32:
        matrix = matrix.astype(np.float32)
    # Center
    centered = matrix - matrix.mean(axis=0, keepdims=True)
    # Thin SVD
    u, s, _ = np.linalg.svd(centered, full_matrices=False)
    components = u[:, :3] * s[:3]
    return components.astype(np.float32)


@dataclass
class SovereignTextIngestor:
    """PTX-native text ingestion built on sovereign bridges + RPN embeddings."""

    languages: Sequence[str] = ("en", "pt", "es", "ja", "zh")
    embedding_store: Path = _DEFAULT_EMBEDDING_STORE

    _graph_builder: GraphCrystallizer = field(init=False)
    _vector_resonator: VectorResonator = field(init=False)
    _oom_guard: OOMSpillManager = field(init=False)
    _rpn_embedder: RPNEmbeddingEngine = field(init=False)
    _has_loaded_store: bool = field(default=False, init=False)

    def __post_init__(self) -> None:
        self._graph_builder = GraphCrystallizer()
        self._vector_resonator = VectorResonator()
        self._oom_guard = OOMSpillManager()
        self._rpn_embedder = RPNEmbeddingEngine(embedding_dim=128)
        self._try_load_embeddings()

    # ------------------------------------------------------------------ #
    # Lifecycle helpers
    # ------------------------------------------------------------------ #
    def _try_load_embeddings(self) -> None:
        if self.embedding_store and self.embedding_store.exists():
            try:
                self._rpn_embedder.load_embeddings(self.embedding_store)
                self._has_loaded_store = True
            except Exception as exc:  # pragma: no cover - defensive logging
                # Keep going with a fresh table; higher layers will refine.
                print(f"[SovereignTextIngestor] Failed to load embeddings: {exc}")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def ingest_vocabulary(self, lang: str, tokens: Sequence[str]) -> np.ndarray:
        """Transform a vocabulary list into 3D Galaxy coordinates."""
        if not tokens:
            raise ValueError("tokens must not be empty")

        embeddings_128 = np.vstack(
            [self._rpn_embedder.embed_word(token) for token in tokens]
        ).astype(np.float32)

        reduced = _reduce_to_3d(embeddings_128)
        reduced -= reduced.min(axis=0, keepdims=True)
        denom = reduced.max(axis=0, keepdims=True)
        denom[denom == 0.0] = 1.0
        return (reduced / denom).astype(np.float32)

    def ingest_sentence(self, lang: str, sentence: str) -> Dict[str, object]:
        """Produce a sovereign representation of a sentence."""
        tokens = [t for t in sentence.strip().split() if t]
        if not tokens:
            raise ValueError("sentence must contain at least one token")

        token_embeddings = [self._rpn_embedder.embed_word(token) for token in tokens]

        node_features: List[np.ndarray] = []
        depth_values: List[int] = []
        denominator = max(len(tokens) - 1, 1)
        for idx, token in enumerate(tokens):
            depth = idx // max(1, len(tokens) // 3)
            depth_values.append(depth)
            emb = token_embeddings[idx]
            feature = np.array(
                [
                    idx / denominator,
                    float(np.mean(emb[:32])),
                    float(np.mean(emb[32:64])),
                ],
                dtype=np.float32,
            )
            node_features.append(feature)

        nodes_np = np.array(node_features, dtype=np.float32).reshape(-1)
        neighbor_features = np.roll(nodes_np, shift=3)
        smoothed = self._graph_builder.crystallize(nodes_np, neighbor_features, ema_rate=0.97)
        node_positions = smoothed.reshape(len(tokens), 3)

        sentence_embedding = self._rpn_embedder.embed_tokens(tokens)
        baseline = np.zeros_like(sentence_embedding)
        sentence_embedding = self._vector_resonator.resonate(
            sentence_embedding.astype(np.float32),
            baseline.astype(np.float32),
            alpha=0.08,
        ).astype(np.float32)

        edges = [(i, i + 1) for i in range(len(tokens) - 1)]
        nodes_info = [
            (token, node_positions[idx].astype(np.float32), depth_values[idx]) for idx, token in enumerate(tokens)
        ]

        return {
            "nodes": nodes_info,
            "edges": edges,
            "embedding_128": sentence_embedding,
            "language": lang,
        }

    def cleanup(self) -> None:
        """Placeholder for API symmetry."""
        # Bridges currently free GPU buffers internally; nothing to do here.
        return

    def save_learned_embeddings(self) -> None:
        """Persist the current RPN embedding table to the default store."""
        if not self.embedding_store:
            raise ValueError("No embedding store configured for SovereignTextIngestor")
        self._rpn_embedder.save_embeddings(self.embedding_store)


__all__ = ["SovereignTextIngestor"]
