from __future__ import annotations

"""
Seed Mode Selector outcome logs by driving the live_server via WebSocket
with dataset metadata + a batch of prompts generated by a remote Ollama LLM.

Usage:
  scripts/k3d_env.sh run python -m knowledge3d.tools.seed_mode_selector \
    --ws ws://127.0.0.1:8765 \
    --gltf viewer/public/galaxy.cross.glb \
    --ollama http://192.168.0.60:11434 \
    --model granite3.3:2b \
    --n 60
"""

import argparse
import asyncio
import json
from pathlib import Path
import os
from typing import List, Tuple, Dict, Set

import websockets  # type: ignore
import time


def load_k3d(glb_path: Path) -> Tuple[List[str], List[str], List[List[str]], List[List[float]], List[Tuple[str, str]]]:
    from pygltflib import GLTF2  # type: ignore
    g = GLTF2().load(str(glb_path))
    prim = g.meshes[0].primitives[0]
    k3d = prim.extras.get("k3d", {})
    ids: List[str] = list(k3d.get("ids", []))
    labels: List[str] = []
    meta = [m if isinstance(m, dict) else {} for m in k3d.get("metadata", [])]
    for i, m in enumerate(meta):
        labels.append((m.get("label") if isinstance(m, dict) else None) or ids[i])
    neighbors: List[List[str]] = k3d.get("neighbors", []) or [[] for _ in range(len(ids))]
    vectors: List[List[float]] = k3d.get("vectors", []) or []
    pairs: List[Tuple[str, str]] = []
    for i, m in enumerate(meta):
        try:
            lab = labels[i]
            txt = str(m.get("text") or "")
            if lab and txt:
                pairs.append((lab, txt[:240]))
        except Exception:
            continue
    return ids, labels, neighbors, vectors, pairs


async def ws_send_json(ws, obj):
    await ws.send(json.dumps(obj))


def build_prompt(n: int) -> str:
    return (
        "You are assisting in evaluating a dual-mode QA system with two modes: "
        "compose (grounded factual, retrieval+stitching) and compose_generate "
        "(creative/explanatory generation grounded by provided contexts). "
        "Output a JSON array with exactly two keys: 'factual' and 'creative'. "
        f"Each key maps to a list with {n//2} diverse, short prompts. "
        "Factual prompts should be navigation/information-seeking (e.g., 'What is UMAP?'). "
        "Creative prompts should be explanatory/synthesis (e.g., 'Explain embeddings with a garden metaphor'). "
        "Return ONLY the JSON object."
    )


def fetch_prompts(ollama_url: str, model: str, n: int) -> List[str]:
    import requests  # type: ignore
    url = ollama_url.rstrip("/") + "/api/generate"
    data = {
        "model": model,
        "prompt": build_prompt(n),
        "stream": False,
        "options": {"temperature": 0.6}
    }
    # Older GPUs may take longer to load a model on first call
    r = requests.post(url, json=data, timeout=240)
    r.raise_for_status()
    out = r.json()
    txt = out.get("response") or out.get("data") or ""
    # Try parse JSON; if not, fall back to simple lines
    qs: List[str] = []
    try:
        js = json.loads(txt)
        if isinstance(js, dict):
            for k in ("factual", "creative"):
                if isinstance(js.get(k), list):
                    for s in js[k]:
                        s = str(s).strip()
                        if s:
                            qs.append(s)
    except Exception:
        for line in txt.splitlines():
            line = line.strip("- *\t ")
            if len(line) >= 8 and not line.lower().startswith("json"):
                qs.append(line)
    # Dedup and cap
    seen = set(); out_q = []
    for q in qs:
        if q in seen:
            continue
        seen.add(q); out_q.append(q)
        if len(out_q) >= n:
            break
    return out_q


async def main_async(ws_url: str, glb: Path, n: int, ollama: str, model: str) -> None:
    ids, labels, neighbors, vectors, pairs = load_k3d(glb)
    # Trim the dataset_graph payload to avoid WS 1009 (message too big)
    # Default cap ~1200 nodes; configurable via K3D_SEED_GRAPH_MAX
    try:
        max_graph = max(200, int(os.getenv("K3D_SEED_GRAPH_MAX", "1200")))
    except Exception:
        max_graph = 1200
    if len(ids) > max_graph:
        step = max(1, len(ids) // max_graph)
        sel_idx = list(range(0, len(ids), step))[:max_graph]
        id_map: Dict[int, int] = {old: i for i, old in enumerate(sel_idx)}
        sel_set: Set[int] = set(sel_idx)
        ids_s = [ids[i] for i in sel_idx]
        labels_s = [labels[i] for i in sel_idx]
        # Keep neighbors within selection; remap by label/id value (server expects ids list of strings)
        neigh_s: List[List[str]] = []
        for i in sel_idx:
            row = neighbors[i] if i < len(neighbors) else []
            # Neighbor rows are ids (strings) per K3D; filter by membership in ids_s
            try:
                keep = [nid for nid in row if nid in ids_s]
            except Exception:
                keep = []
            neigh_s.append(keep)
        # Positions are optional (3D triples)
        vec_s: List[List[float]] = []
        if isinstance(vectors, list) and vectors and isinstance(vectors[0], (list, tuple)):
            try:
                vec_s = [vectors[i] for i in sel_idx]
            except Exception:
                vec_s = []
        ids, labels, neighbors, vectors = ids_s, labels_s, neigh_s, vec_s
    prompts = fetch_prompts(ollama, model, n)
    # More tolerant connect: retry for ~60s with growing delay
    last_exc = None
    for attempt in range(1, 9):
        try:
            async with websockets.connect(ws_url, open_timeout=90) as ws:
                # Send dataset graph
                await ws_send_json(ws, {
                    "type": "event",
                    "event": {
                        "kind": "dataset_graph",
                        "ids": ids,
                        "neighbors": neighbors,
                        "labels": labels,
                        "positions": vectors,
                    }
                })
                # Send snippets (truncated)
                await ws_send_json(ws, {
                    "type": "event",
                    "event": {
                        "kind": "dataset_snippets",
                        "pairs": pairs[:1024]
                    }
                })
                # Send prompts as /ask commands
                for i, q in enumerate(prompts):
                    await ws_send_json(ws, {"type": "chat", "from": "seed", "text": f"/ask {q}"})
                    # Allow more time for older GPUs; backoff slightly as we go
                    await asyncio.sleep(0.25 + 0.02 * i)
                # If we got here, seeding succeeded; exit loop
                last_exc = None
                break
        except Exception as e:
            last_exc = e
            await asyncio.sleep(min(2 * attempt, 10))
    if last_exc is not None:
        raise RuntimeError(f"WS connect failed to {ws_url}: {last_exc}")


def main() -> None:  # pragma: no cover
    ap = argparse.ArgumentParser(description="Seed Mode Selector outcomes via WS + Ollama")
    ap.add_argument("--ws", required=True, help="WebSocket URL (e.g., ws://127.0.0.1:8765)")
    ap.add_argument("--gltf", required=True, help="House GLB to derive graph + snippets")
    ap.add_argument("--ollama", default="http://192.168.0.60:11434")
    ap.add_argument("--model", default="granite3.3:2b")
    ap.add_argument("--n", type=int, default=60)
    args = ap.parse_args()
    asyncio.run(main_async(args.ws, Path(args.gltf), int(args.n), str(args.ollama), str(args.model)))


if __name__ == "__main__":
    main()
