"""Organizer stars for the Tool Manual book galaxy."""

from __future__ import annotations

from ._house_utils import surface_forms
from .meaning_star import MeaningCentricStar


def _book_star(
    *,
    star_id: str,
    meaning_class: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str] | None = None,
    grammar_refs: list[str] | None = None,
    component_refs: list[str] | None = None,
) -> MeaningCentricStar:
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class=meaning_class,
        meaning_rpn=meaning_rpn,
        domain="Book/ToolManual",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        taxonomy_refs=list(taxonomy_refs or []),
        grammar_refs=list(grammar_refs or []),
        component_refs=list(component_refs or []),
        behavior_rpn="OPEN NAVIGATE SECTION REFERENCE_FOUNDATIONS",
        house_room="House/Library",
        confidence=1,
        polarity=1,
    )


TOOL_MANUAL_ENTRIES: list[MeaningCentricStar] = [
    _book_star(
        star_id="toolbook_ch1_math",
        meaning_class="chapter",
        meaning_rpn="CHAPTER MATH CORE WORKERS CASCADE",
        title_en="Chapter 1 Math Core Tools",
        title_pt="Capitulo 1 Ferramentas do Nucleo Matematico",
        title_ja="第1章 数学コアツール",
        taxonomy_refs=[
            "concept_tool",
            "tool_mathcore_tier1_scalar_worker_worker_v1",
            "tool_mathcore_tier2_vector_worker_v1",
            "tool_mathcore_tier3_master_v1",
            "tool_mathcore_spawn_cascade_v1",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
        component_refs=[
            "toolbook_sec1_scalar",
            "toolbook_sec1_vector",
            "toolbook_sec1_orchestration",
            "toolbook_page_cascade_pattern",
            "toolbook_page_house_scenes",
        ],
    ),
    _book_star(
        star_id="toolbook_sec1_scalar",
        meaning_class="section",
        meaning_rpn="SECTION SCALAR WORKER SMALL CHEAP LOOPS",
        title_en="Scalar Workers",
        title_pt="Workers Escalares",
        title_ja="スカラワーカー",
        taxonomy_refs=[
            "tool_mathcore_tier1_scalar_worker_worker_v1",
            "tool_codec_ternary_blocks_v1",
            "tool_codec_audio_mdct_v1",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="toolbook_sec1_vector",
        meaning_class="section",
        meaning_rpn="SECTION VECTOR WORKER SIGNAL GRID",
        title_en="Vector Workers",
        title_pt="Workers Vetoriais",
        title_ja="ベクトルワーカー",
        taxonomy_refs=[
            "tool_mathcore_tier2_vector_worker_v1",
            "tool_codec_video_dct8_grid_v1",
            "tool_signal_audio_spectrogram_v1",
            "tool_signal_spectrogram_surface_v1",
        ],
        grammar_refs=["rate_application"],
    ),
    _book_star(
        star_id="toolbook_sec1_orchestration",
        meaning_class="section",
        meaning_rpn="SECTION ORCHESTRATION MASTER SPAWN CASCADE",
        title_en="Orchestration",
        title_pt="Orquestracao",
        title_ja="オーケストレーション",
        taxonomy_refs=[
            "tool_mathcore_tier3_master_v1",
            "tool_mathcore_spawn_cascade_v1",
            "tool_video_temporal_preview_v1",
            "tool_video_temporal_scene_v1",
        ],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="toolbook_page_cascade_pattern",
        meaning_class="page",
        meaning_rpn="PAGE CASCADE PATTERN TOOL FLOW",
        title_en="Page Cascade Pattern",
        title_pt="Pagina Padrao de Cascata",
        title_ja="ページ カスケードパターン",
        taxonomy_refs=[
            "tool_mathcore_spawn_cascade_v1",
            "tool_mathcore_tier1_scalar_worker_worker_v1",
            "tool_mathcore_tier2_vector_worker_v1",
            "tool_mathcore_tier3_master_v1",
            "concept_tool",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="toolbook_page_house_scenes",
        meaning_class="page",
        meaning_rpn="PAGE HOUSE SCENES LIBRARY GARDEN TOUR",
        title_en="Page House Scenes",
        title_pt="Pagina Cenas da Casa",
        title_ja="ページ ハウスシーン",
        taxonomy_refs=[
            "tool_house_library_scene_v1",
            "tool_house_garden_scene_v1",
            "tool_house_museum_scene_v1",
            "tool_house_replay_scene_v1",
            "tool_house_tour_scene_v1",
        ],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="toolbook_ch2_geometry",
        meaning_class="chapter",
        meaning_rpn="CHAPTER GEOMETRY PROFILES BOUNDS MESH",
        title_en="Chapter 2 Geometry and Construction",
        title_pt="Capitulo 2 Geometria e Construcao",
        title_ja="第2章 幾何と構築",
        taxonomy_refs=[
            "concept_tool",
            "tool_geom_bbox_crop_v1",
            "tool_geom_profile_prep_v1",
            "tool_fusion_contour_to_mesh_v1",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
        component_refs=[
            "toolbook_sec2_profiles",
            "toolbook_sec2_bounding",
            "toolbook_page_mesh_fusion",
            "toolbook_page_surface_projection",
            "toolbook_page_timeline_surfaces",
        ],
    ),
    _book_star(
        star_id="toolbook_sec2_profiles",
        meaning_class="section",
        meaning_rpn="SECTION PROFILES LATHE EXTRUDE SWEEP",
        title_en="Profiles",
        title_pt="Perfis",
        title_ja="プロファイル",
        taxonomy_refs=[
            "tool_geom_profile_prep_v1",
            "tool_geom_profile_lathe_mesh_v1",
            "tool_geom_profile_extrude_mesh_v1",
            "tool_geom_profile_sweep_mesh_v1",
        ],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="toolbook_sec2_bounding",
        meaning_class="section",
        meaning_rpn="SECTION BOUNDING CROP ALIGN SPACE",
        title_en="Bounding",
        title_pt="Limitacao",
        title_ja="境界",
        taxonomy_refs=[
            "tool_geom_bbox_crop_v1",
            "tool_fusion_contour_to_mesh_v1",
            "tool_fusion_surface_material_projection_v1",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="toolbook_page_mesh_fusion",
        meaning_class="page",
        meaning_rpn="PAGE MESH FUSION CONTOUR MATERIAL",
        title_en="Page Mesh Fusion",
        title_pt="Pagina Fusao de Malha",
        title_ja="ページ メッシュ融合",
        taxonomy_refs=[
            "tool_fusion_contour_to_mesh_v1",
            "tool_fusion_surface_material_projection_v1",
            "tool_fusion_signal_surface_material_v1",
            "concept_visual_art",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="toolbook_page_surface_projection",
        meaning_class="page",
        meaning_rpn="PAGE SURFACE PROJECTION UI WORLD",
        title_en="Page Surface Projection",
        title_pt="Pagina Projecao de Superficie",
        title_ja="ページ サーフェス投影",
        taxonomy_refs=[
            "tool_fusion_surface_material_ui_animation_v1",
            "tool_fusion_surface_material_world_animation_v1",
            "tool_fusion_surface_material_ui_scene_v1",
            "tool_fusion_surface_material_world_scene_v1",
        ],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="toolbook_page_timeline_surfaces",
        meaning_class="page",
        meaning_rpn="PAGE TIMELINE SURFACES SIGNAL WORLD",
        title_en="Page Timeline Surfaces",
        title_pt="Pagina Superficies Temporais",
        title_ja="ページ 時系列サーフェス",
        taxonomy_refs=[
            "tool_fusion_surface_material_timeline_v1",
            "tool_fusion_signal_surface_material_timeline_v1",
            "tool_fusion_signal_surface_material_ui_animation_v1",
            "tool_fusion_signal_surface_material_world_animation_v1",
        ],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="toolbook_ch3_media",
        meaning_class="chapter",
        meaning_rpn="CHAPTER MEDIA PAINT AUDIO CODEC",
        title_en="Chapter 3 Media and Codecs",
        title_pt="Capitulo 3 Midia e Codecs",
        title_ja="第3章 メディアとコーデック",
        taxonomy_refs=[
            "concept_tool",
            "tool_paint_gradient_backdrop_v1",
            "tool_signal_audio_spectrogram_v1",
            "tool_codec_ternary_blocks_v1",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
        component_refs=[
            "toolbook_sec3_visual",
            "toolbook_sec3_audio",
            "toolbook_page_encoding",
            "toolbook_page_palette_and_filters",
        ],
    ),
    _book_star(
        star_id="toolbook_sec3_visual",
        meaning_class="section",
        meaning_rpn="SECTION VISUAL PAINT PALETTE FILTER",
        title_en="Visual Tools",
        title_pt="Ferramentas Visuais",
        title_ja="視覚ツール",
        taxonomy_refs=[
            "tool_paint_gradient_backdrop_v1",
            "tool_paint_filter_stack_v1",
            "tool_paint_composite_edge_v1",
            "tool_paint_palette_contrastive_v1",
            "tool_paint_gradient_contrastive_v1",
            "tool_paint_gradient_cascade_v1",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="toolbook_sec3_audio",
        meaning_class="section",
        meaning_rpn="SECTION AUDIO SIGNAL SPECTROGRAM CODEC",
        title_en="Audio Tools",
        title_pt="Ferramentas de Audio",
        title_ja="音声ツール",
        taxonomy_refs=[
            "tool_signal_audio_spectrogram_v1",
            "tool_signal_spectrogram_surface_v1",
            "tool_codec_audio_mdct_v1",
            "tool_fusion_signal_surface_material_v1",
        ],
        grammar_refs=["rate_application"],
    ),
    _book_star(
        star_id="toolbook_page_encoding",
        meaning_class="page",
        meaning_rpn="PAGE ENCODING BLOCKS VIDEO AUDIO",
        title_en="Page Encoding",
        title_pt="Pagina Codificacao",
        title_ja="ページ 符号化",
        taxonomy_refs=[
            "tool_codec_ternary_blocks_v1",
            "tool_codec_video_dct8_grid_v1",
            "tool_codec_audio_mdct_v1",
            "tool_video_temporal_preview_v1",
            "tool_video_temporal_scene_v1",
        ],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="toolbook_page_palette_and_filters",
        meaning_class="page",
        meaning_rpn="PAGE PALETTE FILTERS SIGNAL MATERIAL",
        title_en="Page Palette and Filters",
        title_pt="Pagina Paleta e Filtros",
        title_ja="ページ パレットとフィルタ",
        taxonomy_refs=[
            "tool_paint_palette_contrastive_v1",
            "tool_paint_filter_stack_v1",
            "tool_fusion_signal_surface_material_v1",
            "tool_fusion_surface_material_projection_v1",
        ],
        grammar_refs=["comparison_delta"],
    ),
]


__all__ = ["TOOL_MANUAL_ENTRIES"]
