"""Organizer stars for the Language Foundations book galaxy."""

from __future__ import annotations

from ._house_utils import surface_forms
from .meaning_star import MeaningCentricStar


def _book_star(
    *,
    star_id: str,
    meaning_class: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str] | None = None,
    grammar_refs: list[str] | None = None,
    component_refs: list[str] | None = None,
) -> MeaningCentricStar:
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class=meaning_class,
        meaning_rpn=meaning_rpn,
        domain="Book/LanguageFoundations",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        taxonomy_refs=list(taxonomy_refs or []),
        grammar_refs=list(grammar_refs or []),
        component_refs=list(component_refs or []),
        behavior_rpn="OPEN NAVIGATE SECTION REFERENCE_FOUNDATIONS",
        house_room="House/Library",
        confidence=1,
        polarity=1,
    )


LANGUAGE_FOUNDATIONS_ENTRIES: list[MeaningCentricStar] = [
    _book_star(
        star_id="langbook_ch1_symbols",
        meaning_class="chapter",
        meaning_rpn="CHAPTER SYMBOLS SCRIPT FORMS WRITING",
        title_en="Chapter 1 Symbols",
        title_pt="Capitulo 1 Simbolos",
        title_ja="第1章 記号",
        taxonomy_refs=["concept_language", "seed_word_en_language", "seed_word_pt_linguagem", "seed_word_ja_gengo"],
        component_refs=[
            "langbook_sec1_multilingual_forms",
            "langbook_sec1_sound_to_mark",
            "langbook_page_symbol_bridge",
        ],
    ),
    _book_star(
        star_id="langbook_sec1_multilingual_forms",
        meaning_class="section",
        meaning_rpn="SECTION MULTILINGUAL FORMS WORD SURFACE",
        title_en="Multilingual Forms",
        title_pt="Formas Multilingues",
        title_ja="多言語の形",
        taxonomy_refs=["seed_word_en_language", "seed_word_pt_linguagem", "seed_word_ja_gengo"],
        grammar_refs=["grammar_numeric_literal"],
    ),
    _book_star(
        star_id="langbook_sec1_sound_to_mark",
        meaning_class="section",
        meaning_rpn="SECTION SOUND TO MARK PRONUNCIATION ALIGN",
        title_en="Sound to Mark",
        title_pt="Som para Marca",
        title_ja="音からしるしへ",
        taxonomy_refs=["concept_sound", "concept_language"],
        grammar_refs=["answer_final_stack"],
    ),
    _book_star(
        star_id="langbook_page_symbol_bridge",
        meaning_class="page",
        meaning_rpn="PAGE SYMBOL BRIDGE LOOK SEE SPEAK",
        title_en="Page Symbol Bridge",
        title_pt="Pagina Ponte de Simbolos",
        title_ja="ページ 記号の橋",
        taxonomy_refs=["concept_visual_art", "concept_sound", "concept_language"],
    ),
    _book_star(
        star_id="langbook_ch2_words",
        meaning_class="chapter",
        meaning_rpn="CHAPTER WORDS REFERENCE COUNTING COMPOSITION",
        title_en="Chapter 2 Words",
        title_pt="Capitulo 2 Palavras",
        title_ja="第2章 単語",
        taxonomy_refs=["word_zero", "word_one", "word_two", "word_three"],
        component_refs=[
            "langbook_sec2_counting_words",
            "langbook_sec2_reference_words",
            "langbook_sec2_composition",
        ],
    ),
    _book_star(
        star_id="langbook_sec2_counting_words",
        meaning_class="section",
        meaning_rpn="SECTION COUNTING WORDS NUMBER LEXEMES",
        title_en="Counting Words",
        title_pt="Palavras de Contagem",
        title_ja="数える言葉",
        taxonomy_refs=["word_zero", "word_one", "word_two", "word_three", "word_four", "word_five"],
        grammar_refs=["grammar_numeric_literal"],
    ),
    _book_star(
        star_id="langbook_sec2_reference_words",
        meaning_class="section",
        meaning_rpn="SECTION REFERENCE WORDS LEFT EACH AFTER",
        title_en="Reference Words",
        title_pt="Palavras de Referencia",
        title_ja="参照語",
        taxonomy_refs=["word_zero", "word_one", "word_two"],
        grammar_refs=["consume_from_total", "sequential_computation"],
    ),
    _book_star(
        star_id="langbook_sec2_composition",
        meaning_class="section",
        meaning_rpn="SECTION WORD COMPOSITION PATTERN SEQUENCE",
        title_en="Word Composition",
        title_pt="Composicao de Palavras",
        title_ja="語の構成",
        taxonomy_refs=["concept_language", "concept_tool"],
        grammar_refs=["pattern_arithmetic_next", "pattern_geometric_next"],
    ),
    _book_star(
        star_id="langbook_ch3_grammar",
        meaning_class="chapter",
        meaning_rpn="CHAPTER GRAMMAR LITERAL PATTERN COMPARISON",
        title_en="Chapter 3 Grammar",
        title_pt="Capitulo 3 Gramatica",
        title_ja="第3章 文法",
        taxonomy_refs=["concept_language", "concept_mathematics"],
        component_refs=[
            "langbook_sec3_literals",
            "langbook_sec3_sequences",
            "langbook_sec3_comparison",
            "langbook_page_emit_answer",
        ],
    ),
    _book_star(
        star_id="langbook_sec3_literals",
        meaning_class="section",
        meaning_rpn="SECTION LITERALS TOKENS VALUES BINDING",
        title_en="Literals and Values",
        title_pt="Literais e Valores",
        title_ja="リテラルと値",
        taxonomy_refs=["word_zero", "word_one", "word_two", "num_0", "num_1", "num_2"],
        grammar_refs=["grammar_numeric_literal"],
    ),
    _book_star(
        star_id="langbook_sec3_sequences",
        meaning_class="section",
        meaning_rpn="SECTION SEQUENCE ORDER THEN AFTER",
        title_en="Sequence Rules",
        title_pt="Regras de Sequencia",
        title_ja="順序規則",
        taxonomy_refs=["concept_language", "concept_growth"],
        grammar_refs=["sequential_computation", "pattern_arithmetic_next"],
    ),
    _book_star(
        star_id="langbook_sec3_comparison",
        meaning_class="section",
        meaning_rpn="SECTION COMPARISON DELTA PERCENTAGE",
        title_en="Comparison and Percentage",
        title_pt="Comparacao e Percentagem",
        title_ja="比較と百分率",
        taxonomy_refs=["num_10", "num_50", "num_100"],
        grammar_refs=["comparison_delta", "percentage_application"],
    ),
    _book_star(
        star_id="langbook_page_emit_answer",
        meaning_class="page",
        meaning_rpn="PAGE EMIT ANSWER STACK FINAL FORM",
        title_en="Page Emit the Answer",
        title_pt="Pagina Emitir a Resposta",
        title_ja="ページ 答えを出す",
        taxonomy_refs=["concept_language", "concept_self_reflection"],
        grammar_refs=["answer_final_stack"],
    ),
    _book_star(
        star_id="langbook_ch4_expression",
        meaning_class="chapter",
        meaning_rpn="CHAPTER EXPRESSION TRANSLATION BRIDGE PRACTICE",
        title_en="Chapter 4 Expression",
        title_pt="Capitulo 4 Expressao",
        title_ja="第4章 表現",
        taxonomy_refs=["concept_language", "concept_sound", "concept_visual_art"],
        component_refs=[
            "langbook_sec4_translation_bridges",
            "langbook_sec4_reasoning_words",
            "langbook_page_reading_practice",
        ],
    ),
    _book_star(
        star_id="langbook_sec4_translation_bridges",
        meaning_class="section",
        meaning_rpn="SECTION TRANSLATION BRIDGE EN PT JA",
        title_en="Translation Bridges",
        title_pt="Pontes de Traducao",
        title_ja="翻訳の橋",
        taxonomy_refs=["seed_word_en_language", "seed_word_pt_linguagem", "seed_word_ja_gengo"],
        grammar_refs=["consume_from_total", "rate_application"],
    ),
    _book_star(
        star_id="langbook_sec4_reasoning_words",
        meaning_class="section",
        meaning_rpn="SECTION REASONING WORDS EACH LEFT AFTER",
        title_en="Reasoning Words",
        title_pt="Palavras de Raciocinio",
        title_ja="推論の語",
        taxonomy_refs=["concept_language", "concept_mathematics"],
        grammar_refs=["consume_from_total", "comparison_delta", "percentage_application"],
    ),
    _book_star(
        star_id="langbook_page_reading_practice",
        meaning_class="page",
        meaning_rpn="PAGE READING PRACTICE SEE SPEAK REMEMBER",
        title_en="Page Reading Practice",
        title_pt="Pagina Pratica de Leitura",
        title_ja="ページ 読みの練習",
        taxonomy_refs=["concept_language", "concept_sound", "concept_self_reflection"],
    ),
]


__all__ = ["LANGUAGE_FOUNDATIONS_ENTRIES"]
