"""Organizer stars for the Mathematics Primer book galaxy."""

from __future__ import annotations

from ._house_utils import surface_forms
from .meaning_star import MeaningCentricStar


def _book_star(
    *,
    star_id: str,
    meaning_class: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str] | None = None,
    grammar_refs: list[str] | None = None,
    component_refs: list[str] | None = None,
) -> MeaningCentricStar:
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class=meaning_class,
        meaning_rpn=meaning_rpn,
        domain="Book/MathematicsPrimer",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        taxonomy_refs=list(taxonomy_refs or []),
        grammar_refs=list(grammar_refs or []),
        component_refs=list(component_refs or []),
        behavior_rpn="OPEN NAVIGATE SECTION REFERENCE_FOUNDATIONS",
        house_room="House/Library",
        confidence=1,
        polarity=1,
    )


MATHEMATICS_PRIMER_ENTRIES: list[MeaningCentricStar] = [
    _book_star(
        star_id="mathbook_ch1_numbers",
        meaning_class="chapter",
        meaning_rpn="CHAPTER NUMBERS COUNTING PLACE_VALUE READING_ORDER",
        title_en="Chapter 1 Numbers",
        title_pt="Capitulo 1 Numeros",
        title_ja="第1章 数",
        taxonomy_refs=["concept_mathematics", "num_0", "num_1", "num_2"],
        component_refs=[
            "mathbook_sec1_counting",
            "mathbook_sec1_place_value",
            "mathbook_page_number_words",
        ],
    ),
    _book_star(
        star_id="mathbook_sec1_counting",
        meaning_class="section",
        meaning_rpn="SECTION COUNTING CARDINAL ORDINAL PROGRESSION",
        title_en="Counting and Order",
        title_pt="Contagem e Ordem",
        title_ja="数え方と順序",
        taxonomy_refs=["num_0", "num_1", "num_2", "num_3", "num_4", "num_5"],
        grammar_refs=["grammar_numeric_literal", "count_value"],
    ),
    _book_star(
        star_id="mathbook_sec1_place_value",
        meaning_class="section",
        meaning_rpn="SECTION PLACE VALUE TEN HUNDRED GROUPING",
        title_en="Place Value",
        title_pt="Valor Posicional",
        title_ja="位取り",
        taxonomy_refs=["num_10", "num_20", "num_100", "num_1000"],
        grammar_refs=["grammar_numeric_literal"],
    ),
    _book_star(
        star_id="mathbook_page_number_words",
        meaning_class="page",
        meaning_rpn="PAGE NUMBER WORDS SPOKEN WRITTEN PAIRS",
        title_en="Page Number Words",
        title_pt="Pagina Nomes dos Numeros",
        title_ja="ページ 数のことば",
        taxonomy_refs=["word_zero", "word_one", "word_two", "word_three", "word_four", "word_five"],
    ),
    _book_star(
        star_id="mathbook_ch2_operations",
        meaning_class="chapter",
        meaning_rpn="CHAPTER OPERATIONS ADD SUBTRACT MULTIPLY DIVIDE",
        title_en="Chapter 2 Operations",
        title_pt="Capitulo 2 Operacoes",
        title_ja="第2章 演算",
        taxonomy_refs=["concept_mathematics", "num_6", "num_7", "num_8", "num_9"],
        component_refs=[
            "mathbook_sec2_addition",
            "mathbook_sec2_subtraction",
            "mathbook_sec2_multiplication",
            "mathbook_sec2_division",
        ],
    ),
    _book_star(
        star_id="mathbook_sec2_addition",
        meaning_class="section",
        meaning_rpn="SECTION ADDITION COMBINE TOTAL",
        title_en="Addition",
        title_pt="Adicao",
        title_ja="足し算",
        taxonomy_refs=["num_2", "num_3", "num_4", "num_5"],
        grammar_refs=["sum_all", "consume_from_total"],
    ),
    _book_star(
        star_id="mathbook_sec2_subtraction",
        meaning_class="section",
        meaning_rpn="SECTION SUBTRACTION REMAIN DIFFERENCE",
        title_en="Subtraction",
        title_pt="Subtracao",
        title_ja="引き算",
        taxonomy_refs=["num_6", "num_5", "num_4", "num_3"],
        grammar_refs=["comparison_delta", "consume_from_total"],
    ),
    _book_star(
        star_id="mathbook_sec2_multiplication",
        meaning_class="section",
        meaning_rpn="SECTION MULTIPLICATION GROUPS RATE APPLICATION",
        title_en="Multiplication",
        title_pt="Multiplicacao",
        title_ja="掛け算",
        taxonomy_refs=["num_2", "num_4", "num_8", "num_16"],
        grammar_refs=["rate_application", "sequential_computation"],
    ),
    _book_star(
        star_id="mathbook_sec2_division",
        meaning_class="section",
        meaning_rpn="SECTION DIVISION SHARE SPLIT INVERSE",
        title_en="Division",
        title_pt="Divisao",
        title_ja="割り算",
        taxonomy_refs=["num_12", "num_6", "num_3", "num_2"],
        grammar_refs=["answer_final_stack", "comparison_delta"],
    ),
    _book_star(
        star_id="mathbook_ch3_patterns",
        meaning_class="chapter",
        meaning_rpn="CHAPTER PATTERNS ARITHMETIC GEOMETRIC FRACTION",
        title_en="Chapter 3 Patterns",
        title_pt="Capitulo 3 Padroes",
        title_ja="第3章 パターン",
        taxonomy_refs=["concept_growth", "concept_mathematics", "num_10"],
        component_refs=[
            "mathbook_sec3_arithmetic",
            "mathbook_sec3_geometric",
            "mathbook_sec3_fractions",
        ],
    ),
    _book_star(
        star_id="mathbook_sec3_arithmetic",
        meaning_class="section",
        meaning_rpn="SECTION ARITHMETIC PROGRESSION DIFFERENCE NEXT",
        title_en="Arithmetic Patterns",
        title_pt="Padroes Aritmeticos",
        title_ja="等差パターン",
        taxonomy_refs=["num_1", "num_3", "num_5", "num_7"],
        grammar_refs=["pattern_arithmetic_next"],
    ),
    _book_star(
        star_id="mathbook_sec3_geometric",
        meaning_class="section",
        meaning_rpn="SECTION GEOMETRIC PROGRESSION RATIO NEXT",
        title_en="Geometric Patterns",
        title_pt="Padroes Geometricos",
        title_ja="等比パターン",
        taxonomy_refs=["num_2", "num_4", "num_8", "num_16"],
        grammar_refs=["pattern_geometric_next"],
    ),
    _book_star(
        star_id="mathbook_sec3_fractions",
        meaning_class="section",
        meaning_rpn="SECTION FRACTIONS PART WHOLE RATIO",
        title_en="Fractions and Ratios",
        title_pt="Fracoes e Razoes",
        title_ja="分数と比",
        taxonomy_refs=["num_1", "num_2", "num_3", "num_4"],
        grammar_refs=["percentage_application", "rate_application"],
    ),
    _book_star(
        star_id="mathbook_ch4_shapes",
        meaning_class="chapter",
        meaning_rpn="CHAPTER SHAPES SPACE TRANSFORM PROOF",
        title_en="Chapter 4 Shapes",
        title_pt="Capitulo 4 Formas",
        title_ja="第4章 形",
        taxonomy_refs=["concept_visual_art", "concept_tool", "obj3d_gen_cube", "obj3d_gen_uv_sphere"],
        component_refs=[
            "mathbook_sec4_space",
            "mathbook_sec4_transforms",
            "mathbook_page_proof_habits",
        ],
    ),
    _book_star(
        star_id="mathbook_sec4_space",
        meaning_class="section",
        meaning_rpn="SECTION PLANE SOLID AREA VOLUME",
        title_en="Space and Solids",
        title_pt="Espaco e Solidos",
        title_ja="空間と立体",
        taxonomy_refs=["obj3d_mesh_triangle_face", "obj3d_gen_cube", "obj3d_gen_uv_sphere"],
        grammar_refs=["count_value"],
    ),
    _book_star(
        star_id="mathbook_sec4_transforms",
        meaning_class="section",
        meaning_rpn="SECTION TRANSFORM ROTATE MIRROR APPLY",
        title_en="Transformations",
        title_pt="Transformacoes",
        title_ja="変換",
        taxonomy_refs=["obj3d_xform_translate", "obj3d_xform_scale", "obj3d_xform_apply"],
        grammar_refs=["rotate_90", "mirror_h", "transpose"],
    ),
    _book_star(
        star_id="mathbook_page_proof_habits",
        meaning_class="page",
        meaning_rpn="PAGE PROOF HABITS CHECK STEP VERIFY",
        title_en="Page Proof Habits",
        title_pt="Pagina Habitos de Prova",
        title_ja="ページ 証明の習慣",
        taxonomy_refs=["concept_self_reflection", "concept_mathematics"],
        grammar_refs=["sequential_computation", "answer_final_stack"],
    ),
]


__all__ = ["MATHEMATICS_PRIMER_ENTRIES"]
