"""Organizer stars for the Physics Handbook book galaxy."""

from __future__ import annotations

from ._house_utils import surface_forms
from .meaning_star import MeaningCentricStar


def _book_star(
    *,
    star_id: str,
    meaning_class: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str] | None = None,
    grammar_refs: list[str] | None = None,
    component_refs: list[str] | None = None,
) -> MeaningCentricStar:
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class=meaning_class,
        meaning_rpn=meaning_rpn,
        domain="Book/PhysicsHandbook",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        taxonomy_refs=list(taxonomy_refs or []),
        grammar_refs=list(grammar_refs or []),
        component_refs=list(component_refs or []),
        behavior_rpn="OPEN NAVIGATE SECTION REFERENCE_FOUNDATIONS",
        house_room="House/Library",
        confidence=1,
        polarity=1,
    )


PHYSICS_HANDBOOK_ENTRIES: list[MeaningCentricStar] = [
    _book_star(
        star_id="physicsbook_ch1_motion",
        meaning_class="chapter",
        meaning_rpn="CHAPTER MOTION KINEMATICS TRAJECTORY REASONING",
        title_en="Chapter 1 Motion",
        title_pt="Capitulo 1 Movimento",
        title_ja="第1章 運動",
        taxonomy_refs=["concept_physics", "reality_anchor_college_physics_core", "reality_constant_speed_of_light"],
        grammar_refs=["sequential_computation", "comparison_delta"],
        component_refs=[
            "physicsbook_sec1_position_velocity",
            "physicsbook_sec1_acceleration",
            "physicsbook_sec1_projectiles",
            "physicsbook_page_circular_motion",
        ],
    ),
    _book_star(
        star_id="physicsbook_sec1_position_velocity",
        meaning_class="section",
        meaning_rpn="SECTION POSITION VELOCITY UPDATE EULER",
        title_en="Position and Velocity",
        title_pt="Posicao e Velocidade",
        title_ja="位置と速度",
        taxonomy_refs=[
            "reality_kinematics_position_update_euler",
            "reality_kinematics_velocity_update_euler",
            "reality_kinematics_average_velocity",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
    ),
    _book_star(
        star_id="physicsbook_sec1_acceleration",
        meaning_class="section",
        meaning_rpn="SECTION ACCELERATION DEFINITION CONSTANT CHANGE",
        title_en="Acceleration",
        title_pt="Aceleracao",
        title_ja="加速度",
        taxonomy_refs=[
            "reality_kinematics_acceleration_definition",
            "reality_kinematics_constant_acceleration",
        ],
        grammar_refs=["comparison_delta", "rate_application"],
    ),
    _book_star(
        star_id="physicsbook_sec1_projectiles",
        meaning_class="section",
        meaning_rpn="SECTION PROJECTILES RANGE FLIGHT TWO_DIMENSION",
        title_en="Projectiles",
        title_pt="Projeteis",
        title_ja="投射運動",
        taxonomy_refs=[
            "reality_kinematics_projectile_2d",
            "reality_kinematics_projectile_range",
            "reality_kinematics_projectile_time_of_flight",
        ],
        grammar_refs=["rate_application", "sequential_computation"],
    ),
    _book_star(
        star_id="physicsbook_page_circular_motion",
        meaning_class="page",
        meaning_rpn="PAGE CIRCULAR MOTION RELATIVE FRAME",
        title_en="Page Circular Motion",
        title_pt="Pagina Movimento Circular",
        title_ja="ページ 円運動",
        taxonomy_refs=[
            "reality_kinematics_uniform_circular_speed",
            "reality_kinematics_relative_velocity",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="physicsbook_ch2_forces",
        meaning_class="chapter",
        meaning_rpn="CHAPTER FORCES ENERGY MOMENTUM WORK",
        title_en="Chapter 2 Forces and Energy",
        title_pt="Capitulo 2 Forcas e Energia",
        title_ja="第2章 力とエネルギー",
        taxonomy_refs=["concept_physics", "reality_law_newton_second", "reality_dynamics_newton_second_law"],
        grammar_refs=["sequential_computation", "comparison_delta", "rate_application"],
        component_refs=[
            "physicsbook_sec2_newton_laws",
            "physicsbook_sec2_energy",
            "physicsbook_sec2_momentum",
            "physicsbook_page_collisions",
        ],
    ),
    _book_star(
        star_id="physicsbook_sec2_newton_laws",
        meaning_class="section",
        meaning_rpn="SECTION NEWTON LAWS FORCE FRICTION SPRING",
        title_en="Newton Laws",
        title_pt="Leis de Newton",
        title_ja="ニュートンの法則",
        taxonomy_refs=[
            "reality_dynamics_newton_second_law",
            "reality_dynamics_friction_force",
            "reality_dynamics_hooke_law",
            "reality_dynamics_torque",
        ],
        grammar_refs=["rate_application", "comparison_delta"],
    ),
    _book_star(
        star_id="physicsbook_sec2_energy",
        meaning_class="section",
        meaning_rpn="SECTION ENERGY POTENTIAL KINETIC CONSERVATION",
        title_en="Energy",
        title_pt="Energia",
        title_ja="エネルギー",
        taxonomy_refs=[
            "reality_dynamics_kinetic_energy",
            "reality_dynamics_potential_energy_gravity",
            "reality_dynamics_energy_conservation",
            "reality_dynamics_work",
            "reality_dynamics_power",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
    ),
    _book_star(
        star_id="physicsbook_sec2_momentum",
        meaning_class="section",
        meaning_rpn="SECTION MOMENTUM IMPULSE CONSERVATION",
        title_en="Momentum",
        title_pt="Momento Linear",
        title_ja="運動量",
        taxonomy_refs=[
            "reality_dynamics_momentum_linear",
            "reality_dynamics_impulse",
            "reality_dynamics_momentum_conservation_1d",
            "reality_dynamics_angular_momentum",
        ],
        grammar_refs=["sequential_computation", "comparison_delta"],
    ),
    _book_star(
        star_id="physicsbook_page_collisions",
        meaning_class="page",
        meaning_rpn="PAGE COLLISIONS CENTER MASS ELASTIC INELASTIC",
        title_en="Page Collisions",
        title_pt="Pagina Colisoes",
        title_ja="ページ 衝突",
        taxonomy_refs=[
            "reality_dynamics_elastic_collision_1d",
            "reality_dynamics_inelastic_collision_1d",
            "reality_dynamics_center_of_mass_velocity",
        ],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="physicsbook_ch3_em",
        meaning_class="chapter",
        meaning_rpn="CHAPTER ELECTRICITY MAGNETISM FIELD CIRCUIT",
        title_en="Chapter 3 Electricity and Magnetism",
        title_pt="Capitulo 3 Eletricidade e Magnetismo",
        title_ja="第3章 電磁気",
        taxonomy_refs=["concept_physics", "reality_em_coulomb_force", "reality_em_lorentz_force"],
        grammar_refs=["rate_application", "sequential_computation"],
        component_refs=[
            "physicsbook_sec3_electrostatics",
            "physicsbook_sec3_circuits",
            "physicsbook_page_induction",
        ],
    ),
    _book_star(
        star_id="physicsbook_sec3_electrostatics",
        meaning_class="section",
        meaning_rpn="SECTION ELECTROSTATICS FIELD POTENTIAL GAUSS",
        title_en="Electrostatics",
        title_pt="Eletrostatica",
        title_ja="静電気",
        taxonomy_refs=[
            "reality_em_coulomb_force",
            "reality_em_electric_field_point",
            "reality_em_electric_potential_point",
            "reality_em_gauss_law",
        ],
        grammar_refs=["rate_application", "comparison_delta"],
    ),
    _book_star(
        star_id="physicsbook_sec3_circuits",
        meaning_class="section",
        meaning_rpn="SECTION CIRCUITS OHM RESISTANCE CAPACITANCE",
        title_en="Circuits",
        title_pt="Circuitos",
        title_ja="回路",
        taxonomy_refs=[
            "reality_em_ohm_current",
            "reality_em_ohm_voltage",
            "reality_em_resistor_power",
            "reality_em_series_resistance",
            "reality_em_parallel_resistance",
            "reality_em_capacitor_charge",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
    ),
    _book_star(
        star_id="physicsbook_page_induction",
        meaning_class="page",
        meaning_rpn="PAGE INDUCTION FORCE FIELD LOOP",
        title_en="Page Induction",
        title_pt="Pagina Inducao",
        title_ja="ページ 誘導",
        taxonomy_refs=[
            "reality_em_faraday_law",
            "reality_em_ampere_law",
            "reality_em_lorentz_force",
        ],
        grammar_refs=["comparison_delta", "rate_application"],
    ),
    _book_star(
        star_id="physicsbook_ch4_thermo",
        meaning_class="chapter",
        meaning_rpn="CHAPTER HEAT THERMODYNAMICS ENGINES ENTROPY",
        title_en="Chapter 4 Heat and Thermodynamics",
        title_pt="Capitulo 4 Calor e Termodinamica",
        title_ja="第4章 熱と熱力学",
        taxonomy_refs=["concept_physics", "reality_thermo_first_law", "reality_thermo_entropy_change"],
        grammar_refs=["sequential_computation", "comparison_delta", "rate_application"],
        component_refs=[
            "physicsbook_sec4_temperature",
            "physicsbook_sec4_energy_transfer",
            "physicsbook_page_engines",
        ],
    ),
    _book_star(
        star_id="physicsbook_sec4_temperature",
        meaning_class="section",
        meaning_rpn="SECTION TEMPERATURE PRESSURE VOLUME GAS",
        title_en="Temperature and Gases",
        title_pt="Temperatura e Gases",
        title_ja="温度と気体",
        taxonomy_refs=[
            "reality_thermo_ideal_gas_temperature",
            "reality_thermo_ideal_gas_pressure",
            "reality_thermo_ideal_gas_volume",
            "reality_thermo_heat_capacity",
        ],
        grammar_refs=["rate_application", "comparison_delta"],
    ),
    _book_star(
        star_id="physicsbook_sec4_energy_transfer",
        meaning_class="section",
        meaning_rpn="SECTION ENERGY TRANSFER HEAT PHASE CHANGE",
        title_en="Energy Transfer",
        title_pt="Transferencia de Energia",
        title_ja="エネルギー移動",
        taxonomy_refs=[
            "reality_thermo_first_law",
            "reality_thermo_conduction_rate",
            "reality_thermo_phase_change_heat",
            "reality_thermo_thermal_energy",
        ],
        grammar_refs=["sequential_computation", "rate_application"],
    ),
    _book_star(
        star_id="physicsbook_page_engines",
        meaning_class="page",
        meaning_rpn="PAGE ENGINES ENTROPY EFFICIENCY LIMIT",
        title_en="Page Engines",
        title_pt="Pagina Motores",
        title_ja="ページ 熱機関",
        taxonomy_refs=[
            "reality_thermo_carnot_efficiency",
            "reality_thermo_entropy_change",
        ],
        grammar_refs=["comparison_delta"],
    ),
]


__all__ = ["PHYSICS_HANDBOOK_ENTRIES"]
