"""Organizer stars for the Biology Atlas book galaxy."""

from __future__ import annotations

from ._house_utils import surface_forms
from .meaning_star import MeaningCentricStar


def _book_star(
    *,
    star_id: str,
    meaning_class: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str] | None = None,
    grammar_refs: list[str] | None = None,
    component_refs: list[str] | None = None,
) -> MeaningCentricStar:
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class=meaning_class,
        meaning_rpn=meaning_rpn,
        domain="Book/BiologyAtlas",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        taxonomy_refs=list(taxonomy_refs or []),
        grammar_refs=list(grammar_refs or []),
        component_refs=list(component_refs or []),
        behavior_rpn="OPEN NAVIGATE SECTION REFERENCE_FOUNDATIONS",
        house_room="House/Library",
        confidence=1,
        polarity=1,
    )


BIOLOGY_ATLAS_ENTRIES: list[MeaningCentricStar] = [
    _book_star(
        star_id="biobook_ch1_cell",
        meaning_class="chapter",
        meaning_rpn="CHAPTER CELL STRUCTURE INFORMATION FLOW",
        title_en="Chapter 1 The Cell",
        title_pt="Capitulo 1 A Celula",
        title_ja="第1章 細胞",
        taxonomy_refs=["concept_biology", "reality_anchor_college_biology_core", "reality_biology_cell_theory"],
        grammar_refs=["sequential_computation"],
        component_refs=[
            "biobook_sec1_cell_structure",
            "biobook_sec1_genetics",
            "biobook_page_dna_rna",
            "biobook_page_cell_systems",
        ],
    ),
    _book_star(
        star_id="biobook_sec1_cell_structure",
        meaning_class="section",
        meaning_rpn="SECTION CELL STRUCTURE THEORY ORGANIZATION",
        title_en="Cell Structure",
        title_pt="Estrutura Celular",
        title_ja="細胞構造",
        taxonomy_refs=["reality_biology_cell_theory", "reality_anchor_college_biology_core"],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="biobook_sec1_genetics",
        meaning_class="section",
        meaning_rpn="SECTION GENETICS INHERITANCE EXPRESSION",
        title_en="Genetics",
        title_pt="Genetica",
        title_ja="遺伝学",
        taxonomy_refs=["reality_biology_genetics_inheritance", "reality_biology_transcription_translation"],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="biobook_page_dna_rna",
        meaning_class="page",
        meaning_rpn="PAGE DNA RNA TRANSCRIPTION TRANSLATION",
        title_en="Page DNA and RNA",
        title_pt="Pagina DNA e RNA",
        title_ja="ページ DNAとRNA",
        taxonomy_refs=["reality_biology_cell_theory", "reality_biology_genetics_inheritance", "reality_biology_transcription_translation"],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="biobook_page_cell_systems",
        meaning_class="page",
        meaning_rpn="PAGE CELL SYSTEMS ENZYMES IMMUNE",
        title_en="Page Cell Systems",
        title_pt="Pagina Sistemas Celulares",
        title_ja="ページ 細胞システム",
        taxonomy_refs=["reality_biology_enzymes_metabolism", "reality_biology_immune_system"],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="biobook_ch2_organisms",
        meaning_class="chapter",
        meaning_rpn="CHAPTER ORGANISMS EVOLUTION ADAPTATION",
        title_en="Chapter 2 Organisms and Evolution",
        title_pt="Capitulo 2 Organismos e Evolucao",
        title_ja="第2章 生物と進化",
        taxonomy_refs=["concept_biology", "concept_growth", "reality_biology_evolution_selection"],
        grammar_refs=["comparison_delta", "sequential_computation"],
        component_refs=[
            "biobook_sec2_evolution",
            "biobook_sec2_homeostasis",
            "biobook_page_adaptation",
            "biobook_page_body_systems",
        ],
    ),
    _book_star(
        star_id="biobook_sec2_evolution",
        meaning_class="section",
        meaning_rpn="SECTION EVOLUTION SELECTION VARIATION",
        title_en="Evolution",
        title_pt="Evolucao",
        title_ja="進化",
        taxonomy_refs=["reality_biology_evolution_selection", "reality_biology_biodiversity_taxonomy"],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="biobook_sec2_homeostasis",
        meaning_class="section",
        meaning_rpn="SECTION HOMEOSTASIS REGULATION FEEDBACK",
        title_en="Homeostasis",
        title_pt="Homeostase",
        title_ja="恒常性",
        taxonomy_refs=["reality_biology_homeostasis", "reality_biology_anatomy_physiology"],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="biobook_page_adaptation",
        meaning_class="page",
        meaning_rpn="PAGE ADAPTATION GROWTH FITNESS",
        title_en="Page Adaptation",
        title_pt="Pagina Adaptacao",
        title_ja="ページ 適応",
        taxonomy_refs=["reality_biology_evolution_selection", "concept_growth"],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="biobook_page_body_systems",
        meaning_class="page",
        meaning_rpn="PAGE BODY SYSTEMS NERVOUS IMMUNE",
        title_en="Page Body Systems",
        title_pt="Pagina Sistemas do Corpo",
        title_ja="ページ 身体系",
        taxonomy_refs=["reality_biology_anatomy_physiology", "reality_biology_neuroscience", "reality_biology_immune_system"],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="biobook_ch3_ecology",
        meaning_class="chapter",
        meaning_rpn="CHAPTER ECOLOGY POPULATIONS ENERGY SYSTEMS",
        title_en="Chapter 3 Ecology",
        title_pt="Capitulo 3 Ecologia",
        title_ja="第3章 生態学",
        taxonomy_refs=["concept_biology", "reality_biology_ecology_populations", "reality_biology_biodiversity_taxonomy"],
        grammar_refs=["comparison_delta", "rate_application"],
        component_refs=[
            "biobook_sec3_populations",
            "biobook_sec3_energy_flow",
            "biobook_page_systems_view",
            "biobook_page_micro_worlds",
            "biobook_page_development",
        ],
    ),
    _book_star(
        star_id="biobook_sec3_populations",
        meaning_class="section",
        meaning_rpn="SECTION POPULATIONS NICHE ECOSYSTEMS",
        title_en="Populations",
        title_pt="Populacoes",
        title_ja="個体群",
        taxonomy_refs=["reality_biology_ecology_populations", "reality_biology_biodiversity_taxonomy"],
        grammar_refs=["rate_application", "comparison_delta"],
    ),
    _book_star(
        star_id="biobook_sec3_energy_flow",
        meaning_class="section",
        meaning_rpn="SECTION ENERGY FLOW ECOLOGY THERMODYNAMICS",
        title_en="Energy Flow",
        title_pt="Fluxo de Energia",
        title_ja="エネルギーの流れ",
        taxonomy_refs=["reality_biology_ecology_populations", "reality_thermo_first_law", "reality_thermo_thermal_energy"],
        grammar_refs=["sequential_computation", "rate_application"],
    ),
    _book_star(
        star_id="biobook_page_systems_view",
        meaning_class="page",
        meaning_rpn="PAGE SYSTEMS VIEW BIOLOGY PHYSICS GROWTH",
        title_en="Page Systems View",
        title_pt="Pagina Visao de Sistemas",
        title_ja="ページ システム視点",
        taxonomy_refs=["concept_biology", "concept_physics", "concept_growth"],
        grammar_refs=["comparison_delta"],
    ),
    _book_star(
        star_id="biobook_page_micro_worlds",
        meaning_class="page",
        meaning_rpn="PAGE MICRO WORLDS MICROBES INTERACTION",
        title_en="Page Micro Worlds",
        title_pt="Pagina Mundos Microscopicos",
        title_ja="ページ 微小世界",
        taxonomy_refs=["reality_biology_microbiology", "reality_biology_enzymes_metabolism"],
        grammar_refs=["sequential_computation"],
    ),
    _book_star(
        star_id="biobook_page_development",
        meaning_class="page",
        meaning_rpn="PAGE DEVELOPMENT EMBRYO DIFFERENTIATION",
        title_en="Page Development",
        title_pt="Pagina Desenvolvimento",
        title_ja="ページ 発生",
        taxonomy_refs=["reality_biology_embryology", "reality_biology_genetics_inheritance"],
        grammar_refs=["sequential_computation"],
    ),
]


__all__ = ["BIOLOGY_ATLAS_ENTRIES"]
