"""Ontology tree branches and leaves for the Knowledge Garden."""

from __future__ import annotations

from ._house_utils import surface_forms
from .meaning_star import MeaningCentricStar


def _branch(
    *,
    star_id: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str],
    component_refs: list[str],
    rotate_x: float = 0.0,
    rotate_z: float = 0.0,
    translate: tuple[float, float, float] = (0.0, 0.0, 0.0),
) -> MeaningCentricStar:
    visual = "0.06 1.2 6 1 GEN_CYLINDER "
    if rotate_x:
        visual += f"{rotate_x:.4f} MAT4_ROTATE_X MAT4_APPLY "
    if rotate_z:
        visual += f"{rotate_z:.4f} MAT4_ROTATE_Z MAT4_APPLY "
    visual += f"{translate[0]:.4f} {translate[1]:.4f} {translate[2]:.4f} MAT4_TRANSLATE MAT4_APPLY"
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class="branch",
        meaning_rpn=meaning_rpn,
        domain="House/Garden/KnowledgeTree",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        visual_rpn=visual,
        taxonomy_refs=taxonomy_refs,
        component_refs=component_refs,
        house_position=translate,
        house_room="House/Garden",
        confidence=1,
        polarity=1,
    )


def _leaf(
    *,
    star_id: str,
    meaning_rpn: str,
    title_en: str,
    title_pt: str,
    title_ja: str,
    taxonomy_refs: list[str],
    translate: tuple[float, float, float],
) -> MeaningCentricStar:
    return MeaningCentricStar(
        star_id=star_id,
        meaning_class="leaf",
        meaning_rpn=meaning_rpn,
        domain="House/Garden/KnowledgeTree",
        surface_forms=surface_forms(title_en, title_pt, title_ja),
        visual_rpn=f"0.08 0 GEN_ICOSPHERE {translate[0]:.4f} {translate[1]:.4f} {translate[2]:.4f} MAT4_TRANSLATE MAT4_APPLY",
        taxonomy_refs=taxonomy_refs,
        house_position=translate,
        house_room="House/Garden",
        confidence=1,
        polarity=1,
    )


KNOWLEDGE_TREE_BRANCHES: list[MeaningCentricStar] = [
    _branch(
        star_id="tree_branch_mathematics",
        meaning_rpn="BRANCH MATHEMATICS DOMAIN_LINK",
        title_en="Mathematics Branch",
        title_pt="Ramo Matematica",
        title_ja="数学の枝",
        taxonomy_refs=["concept_mathematics"],
        component_refs=["tree_leaf_numbers", "tree_leaf_operations", "tree_leaf_patterns"],
        rotate_z=-0.7854,
        translate=(5.50, 1.70, 5.45),
    ),
    _branch(
        star_id="tree_branch_language",
        meaning_rpn="BRANCH LANGUAGE DOMAIN_LINK",
        title_en="Language Branch",
        title_pt="Ramo Linguagem",
        title_ja="言語の枝",
        taxonomy_refs=["concept_language"],
        component_refs=["tree_leaf_characters", "tree_leaf_words", "tree_leaf_grammar"],
        rotate_z=0.7854,
        translate=(4.50, 1.70, 5.45),
    ),
    _branch(
        star_id="tree_branch_physics",
        meaning_rpn="BRANCH PHYSICS DOMAIN_LINK",
        title_en="Physics Branch",
        title_pt="Ramo Fisica",
        title_ja="物理の枝",
        taxonomy_refs=["concept_physics"],
        component_refs=["tree_leaf_motion", "tree_leaf_energy", "tree_leaf_fields"],
        rotate_x=0.7854,
        translate=(5.00, 1.75, 5.90),
    ),
    _branch(
        star_id="tree_branch_biology",
        meaning_rpn="BRANCH BIOLOGY DOMAIN_LINK",
        title_en="Biology Branch",
        title_pt="Ramo Biologia",
        title_ja="生物の枝",
        taxonomy_refs=["concept_biology"],
        component_refs=["tree_leaf_cells", "tree_leaf_ecology", "tree_leaf_growth"],
        rotate_x=-0.7854,
        translate=(5.00, 1.75, 4.10),
    ),
    _branch(
        star_id="tree_branch_tools",
        meaning_rpn="BRANCH TOOLS DOMAIN_LINK",
        title_en="Tools Branch",
        title_pt="Ramo Ferramentas",
        title_ja="道具の枝",
        taxonomy_refs=["concept_tool"],
        component_refs=["tree_leaf_workers", "tree_leaf_geometry", "tree_leaf_media"],
        rotate_x=0.3927,
        rotate_z=-0.3927,
        translate=(5.55, 2.05, 5.15),
    ),
    _leaf(
        star_id="tree_leaf_numbers",
        meaning_rpn="LEAF NUMBERS COUNTING CARDINAL",
        title_en="Numbers Leaf",
        title_pt="Folha Numeros",
        title_ja="数の葉",
        taxonomy_refs=["concept_mathematics", "num_0", "num_1", "num_2"],
        translate=(5.88, 2.30, 5.74),
    ),
    _leaf(
        star_id="tree_leaf_operations",
        meaning_rpn="LEAF OPERATIONS ADD SUBTRACT MULTIPLY",
        title_en="Operations Leaf",
        title_pt="Folha Operacoes",
        title_ja="演算の葉",
        taxonomy_refs=["concept_mathematics", "sum_all", "comparison_delta", "rate_application"],
        translate=(5.66, 2.46, 5.58),
    ),
    _leaf(
        star_id="tree_leaf_patterns",
        meaning_rpn="LEAF PATTERNS PROGRESSION SEQUENCE",
        title_en="Patterns Leaf",
        title_pt="Folha Padroes",
        title_ja="パターンの葉",
        taxonomy_refs=["concept_mathematics", "pattern_arithmetic_next", "pattern_geometric_next"],
        translate=(5.96, 2.58, 5.42),
    ),
    _leaf(
        star_id="tree_leaf_characters",
        meaning_rpn="LEAF CHARACTERS SYMBOLS WRITING",
        title_en="Characters Leaf",
        title_pt="Folha Caracteres",
        title_ja="文字の葉",
        taxonomy_refs=["concept_language", "seed_word_en_language", "seed_word_pt_linguagem", "seed_word_ja_gengo"],
        translate=(4.12, 2.28, 5.74),
    ),
    _leaf(
        star_id="tree_leaf_words",
        meaning_rpn="LEAF WORDS VOCABULARY REFERENCE",
        title_en="Words Leaf",
        title_pt="Folha Palavras",
        title_ja="単語の葉",
        taxonomy_refs=["concept_language", "word_zero", "word_one", "word_two"],
        translate=(4.34, 2.44, 5.58),
    ),
    _leaf(
        star_id="tree_leaf_grammar",
        meaning_rpn="LEAF GRAMMAR RULES EXPRESSIONS",
        title_en="Grammar Leaf",
        title_pt="Folha Gramatica",
        title_ja="文法の葉",
        taxonomy_refs=["concept_language", "grammar_numeric_literal", "answer_final_stack", "sequential_computation"],
        translate=(4.02, 2.56, 5.42),
    ),
    _leaf(
        star_id="tree_leaf_motion",
        meaning_rpn="LEAF MOTION VELOCITY TRAJECTORY",
        title_en="Motion Leaf",
        title_pt="Folha Movimento",
        title_ja="運動の葉",
        taxonomy_refs=["concept_physics", "reality_kinematics_average_velocity", "reality_kinematics_projectile_2d"],
        translate=(5.00, 2.34, 6.16),
    ),
    _leaf(
        star_id="tree_leaf_energy",
        meaning_rpn="LEAF ENERGY HEAT CONSERVATION",
        title_en="Energy Leaf",
        title_pt="Folha Energia",
        title_ja="エネルギーの葉",
        taxonomy_refs=["concept_physics", "reality_dynamics_energy_conservation", "reality_thermo_first_law"],
        translate=(5.18, 2.54, 6.04),
    ),
    _leaf(
        star_id="tree_leaf_fields",
        meaning_rpn="LEAF FIELDS ELECTRIC MAGNETIC FORCE",
        title_en="Fields Leaf",
        title_pt="Folha Campos",
        title_ja="場の葉",
        taxonomy_refs=["concept_physics", "reality_em_electric_field_point", "reality_em_lorentz_force"],
        translate=(4.82, 2.62, 5.96),
    ),
    _leaf(
        star_id="tree_leaf_cells",
        meaning_rpn="LEAF CELLS LIFE STRUCTURE",
        title_en="Cells Leaf",
        title_pt="Folha Celulas",
        title_ja="細胞の葉",
        taxonomy_refs=["concept_biology", "reality_biology_cell_theory", "reality_biology_transcription_translation"],
        translate=(5.00, 2.34, 3.86),
    ),
    _leaf(
        star_id="tree_leaf_ecology",
        meaning_rpn="LEAF ECOLOGY POPULATIONS SYSTEMS",
        title_en="Ecology Leaf",
        title_pt="Folha Ecologia",
        title_ja="生態の葉",
        taxonomy_refs=["concept_biology", "reality_biology_ecology_populations", "reality_thermo_thermal_energy"],
        translate=(5.18, 2.54, 3.98),
    ),
    _leaf(
        star_id="tree_leaf_growth",
        meaning_rpn="LEAF GROWTH ADAPTATION CHANGE",
        title_en="Growth Leaf",
        title_pt="Folha Crescimento",
        title_ja="成長の葉",
        taxonomy_refs=["concept_growth", "concept_biology", "reality_biology_evolution_selection"],
        translate=(4.82, 2.62, 4.04),
    ),
    _leaf(
        star_id="tree_leaf_workers",
        meaning_rpn="LEAF WORKERS CASCADE ORCHESTRATION",
        title_en="Workers Leaf",
        title_pt="Folha Workers",
        title_ja="ワーカーの葉",
        taxonomy_refs=["concept_tool", "tool_mathcore_tier1_scalar_worker_worker_v1", "tool_mathcore_tier3_master_v1"],
        translate=(5.92, 2.56, 5.20),
    ),
    _leaf(
        star_id="tree_leaf_geometry",
        meaning_rpn="LEAF GEOMETRY PROFILES MESH",
        title_en="Geometry Leaf",
        title_pt="Folha Geometria",
        title_ja="幾何の葉",
        taxonomy_refs=["concept_tool", "tool_geom_profile_extrude_mesh_v1", "tool_fusion_contour_to_mesh_v1"],
        translate=(5.78, 2.74, 5.34),
    ),
    _leaf(
        star_id="tree_leaf_media",
        meaning_rpn="LEAF MEDIA SIGNAL CODEC",
        title_en="Media Leaf",
        title_pt="Folha Midia",
        title_ja="メディアの葉",
        taxonomy_refs=["concept_tool", "tool_signal_audio_spectrogram_v1", "tool_codec_video_dct8_grid_v1"],
        translate=(6.02, 2.86, 5.06),
    ),
]


__all__ = ["KNOWLEDGE_TREE_BRANCHES"]
